### ISSUE TITLE
Investigating sonic waveforms

### ISSUE THREAD

**Issue by carlpe** [equinor/dlisio-notebooks#9]
Hi, I have some questions regarding the tutorial notebook on acoustic DLIS data. I have downloaded the file locally and am able to load in the DLIS as such:

![image](https://user-images.githubusercontent.com/54416001/148918145-c9c5b6ce-0e60-4b51-9c17-4f2c59adecdd.png)

Further, I am able to extract the following list of tools:

![image](https://user-images.githubusercontent.com/54416001/148918648-bb2c18ef-3344-47e6-a5e9-b63ddd323446.png)

But when I am trying to get the tool` ".*DSLT.*" `- I get this error.

![image](https://user-images.githubusercontent.com/54416001/148917864-0bb83eaf-e202-4346-b163-b672cf9b0b4f.png)

If I change the tool from `".*DSLT.*"` to `"DSLT-H"`, I am able to proceed.

![image](https://user-images.githubusercontent.com/54416001/148917886-9a744b0d-8e89-4cbe-8e57-0dc652edbe9f.png)

And I can see the two Waveform data WF1 and WF2 in frame 20B.

![image](https://user-images.githubusercontent.com/54416001/148917937-313483e7-ff6c-4951-b27f-9c9d84c80e1b.png)

But when I try the next step in order to explore the contents of the aforementioned waveforms, I get the following error.

![image](https://user-images.githubusercontent.com/54416001/148917950-072b1a43-eb94-47f1-88be-2a9d46bb64c6.png)

Please elaborate and explain if I am missing something.

**Comment by ErlendHaa** [comment]
What version of dlisio do you have?

**Comment by carlpe** [comment]
![image](https://user-images.githubusercontent.com/54416001/148927246-e003930d-f273-4a39-b106-af1aaf1a9195.png)

**Comment by carlpe** [comment]
When using version 0.1.16 I get this error:

![image](https://user-images.githubusercontent.com/54416001/148932117-9150180b-89a6-45f4-bb25-58247c8b99db.png)

**Comment by ErlendHaa** [comment]
As you probably have noticed then, the notebook is a bit outdated. There has been some breaking changes to `dlis.LogicalFile` since `v0.1.16`. In particular, we have striped `f.object` for regex support and `f.match` got replaced by `f.find`. 

To access the tool `DSLT-H` either do as you suggested, use `f.object` without regex matching:
```
dslt = f.object('TOOL', 'DSLT-H')
```
or if you want to find all objects matching the regex `.*DSLT-H.*`
```
dslts = f.find('TOOL', '.*DSLT.*')
```

**Comment by ErlendHaa** [comment]
It seams we have made `f.object()` case sensitive.  So you have to uppercase the type: `frame20B = f.object('FRAME', '20B')`

This is arguably a bug tho

**Comment by carlpe** [comment]
Fantastic, It works now.

**Comment by ErlendHaa** [comment]
And for completeness, in dlisio `v0.1.16` the correct way to load the file was:

`f, *tail = dlisio.load('...')` not `f, *tail = dlis.load('...')`

There's been a lot of breaking changes to the library since the release of this notebook, so I understand the confusion/fustration.

I'll see if I have time to update it to `v0.3.5`

**Comment by carlpe** [comment]
Ok good. Thanks for the help! 
Do not be surprised if I have some more questions at a later stage.
